### ISSUE TITLE
Usefulness of type condition errors 

### ISSUE THREAD

**Issue by PavelVozenilek** [jfecher/ante#11]
This example got me thinking:

```
type Teen =
  u8 age  in 10 .. 19
  Str name  where name.length > 0
//TypeConditionErr
let sara = Teen(18, "")
```

How much useful is this feature?

I'll ignore simpler things like pointer nulability checking and enforcing integer ranges and will write about string restrictions and more complicated compile time checks.

1. Programs usually do not have that many literals in code. Complex data are read from some external source, not hardcoded. Even hardcoded strings may go first through internationalization layer. 

2. The checking won't be so simple. 

 Instead of  `where name.length > 0` one may want a function which decides that  `Jon Snow` is a valid name and `ougs872kjgs` is not. One would not create such a complicated function only for rare compile time use.

 Complicated checks also take time and one may not want compiler to insert them automatically, e.g every time a structure is copied. (This is IMHO the main problem with language level preconditions, postconditions and class invariants: they are nice and all but get invoked over and over, even when one knows this is unneccessary.)
 

3. Useful checking may not be possible during compile time. The check could be whether the name is actually present in some database or whether the name is unique among all similar data loaded into memory.

**Comment by jfecher** [comment]
All range restrictions and where clauses are checked whenever the value changes at runtime, ensuring the values can never be invalid.  They are only done at compile time if possible.  This feature is mainly for security critical applications that can sacrifice a bit of speed for safety.
