### ISSUE TITLE
captured value will be destroyed

### ISSUE THREAD

**Issue by eldesh** [jfecher/ante#141]
I found a compiler bug.
The compiler accepts the following code but outputs a broken program.
It mysteriously destroys the captured value v.

# Environment

- os: debian
- ante: 0.1.1 (commit: 2de60ca)

# Code

```
f (v:float) : float =
  go x =
    if x < 2.0 then x
    else
      print v
      go (x / 2.0)
  go (v / 2.0)

x = f 123.0
```

# Output

```
ante test.an
123.0
61.5000
30.7500
15.3750
7.6875
```

**Comment by jfecher** [comment]
Took a quick look at the hir and cranelift/llvm irs. Looks like the closure value is being referenced to like a normal lambda without its environment within the closure's recursive calls
