### ISSUE TITLE
string literals concatenation

### ISSUE THREAD

**Issue by PavelVozenilek** [jfecher/ante#15]
In file `strInterpolation.an ` I noticed line:

`print( "Hello, " ++ getMyString() ++ "!")
`

Why is the `++` needed here? These string has to be concatenated, nothing else can be done here. Why not the ability to omit this operator when the context is clear (and it is also clear where expression ends)?

`print( "Hello, " getMyString()  "!")
`

This would help e.g with generating HTML fragments, making it easier to the eyes.

**Comment by jfecher** [comment]
omitting the ++ makes the call to getMyString ambiguous in your example.  Is it a call to getMy String with just an empty tuple parameter () or is it a call with the parameters () and "!"

**Comment by jfecher** [comment]
Also, perhaps more importantly the parser cannot distinguish between the proposed shorthand concatenation and a function call (Ante uses ML syntax for most function calls)

**Comment by PavelVozenilek** [comment]
Hmm, I imagined something like ASCII art to generate HTML.
