### ISSUE TITLE
Building: llvmenv panics and looks abandoned

### ISSUE THREAD

**Issue by tbmreza** [jfecher/ante#151]
llvmenv panics when running `llvmenv build-entry -G Makefile -j7 13.0.0` building step.

```
[ 25%] Linking CXX static library ../../libLLVMDebugInfoCodeView.a
[ 25%] Built target LLVMDebugInfoCodeView
gmake: *** [Makefile:156: all] Error 2
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: CommandError { errno: 2, cmd: "\"cmake\" \"--build\" \"/home/rezahandzalah/.cache/llvmenv/13.0.0/build\" \"--target\" \"install\" \"--\" \"-j\" \"7\"", stdout: None, stderr: None }', /home/rezahandzalah/.cargo/registry/src/github.com-1ecc6299db9ec823/llvmenv-0.3.2/src/bin/llvmenv.rs:173:32
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Perhaps demote it as building method, putting the cmake method higher in the Building section list of the readme?

Still related to llvmenv but less important, I would add a note about using it that reads something like this in the readme:
<i>
amd64 architecture users might stumble upon `'openssl/opensslconf.h' file not found` error when installing llvmenv because apparently [the files were moved](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=733644#10).

$ cp /usr/include/x86_64-linux-gnu/openssl/{opensslconf,configuration}.h /usr/include/openssl/
</i>

**Comment by jfecher** [comment]
It is indeed abandoned. I tried maintaining it once upon a time but quickly realized I didn't have the time for both projects. I think it should likely be removed from the readme entirely.

**Comment by jfecher** [comment]
Removed all mentions of llvmenv
