### ISSUE TITLE
Compiler crash when trying to access field of unspecified row-polymorphic type

### ISSUE THREAD

**Issue by PROMETHIA-27** [jfecher/ante#156]
A field access of an expression that is never constrained to a concrete type leads to a compiler panic:
`thread 'main' panicked at 'internal error: entered unreachable code: get_field_index called with type { field: b, .. } that doesn't have a 'field' field', src\hir\monomorphisation.rs:1485:18`

Minimal repro:
```
never = panic "crashy"
a = never.field
```

**Comment by jfecher** [comment]
Fixed: It was indeed a simple missed match case in get_field_index
