### ISSUE TITLE
first attempt

### ISSUE THREAD

**Issue by PavelVozenilek** [jfecher/ante#19]
I tried to compile the tiny test:

```
print "Start"  


let x1 = 250u8
print x1

print "End"  
```

Screenshot of the result:
http://i.imgur.com/p1svZPF.png

Got 2 small problems:

1. Console switched to colors, OK, but i did not switch back.  See screenshot.
2. Error message I got is uncomprehensible.

```
O:\ante\ante-master\bin>ante test.an

test.an: 5,7-8  error: Argument 1 of function is a(n) u8 but was declared to be a(n) c8* and there is no known implicit
cast
print x1
      ^^

Compilation aborted.

```

**Comment by jfecher** [comment]
I changed the color to darkwhite, see if that looks any better.
