### ISSUE TITLE
expression quietly overflows

### ISSUE THREAD

**Issue by PavelVozenilek** [jfecher/ante#20]
I am curious how numeric expression work in ante:

```
print "Start"  

let x1 = 250u8
let x2 = 250u8
let x3 = 250u8


var x4 = 999u8

x4 = (x1 * x2) / x3
printf "x4 = %u\n" x4


print "End"  
```

The result is 0, instead of the correct 1.  Perhaps expressions should automatically (unless it can be proved overflow cannot happen) use the highest hardware supported numeral type to avoid quiet overflows and truncating. It is different from C rules but it should not be much slower.

Alternatively the C-like truncation may be default but with option to override it with something like:

```
no_overflow {
   .. calculations
} else {
  ... overflow/truncation happened
}

```
IIRC C# uses someting like this.

**Comment by PavelVozenilek** [comment]
I also got this error:

```
print "Start"  


let x1 = 1u8
let x2 = 1u8
let x3 = 1u8


var x4 = 999u8

x4 = (2 * x1 * x2) / x3

printf "x4 = %u\n" x4


print "End"  

```


results in:
```

O:\ante\ante-master\bin>ante test.an
test.an: 11,4-23        error: Cannot assign expression of type i32 to a variable of type i8
x4 = (2 * x1 * x2) / x3
   ^^^^^^^^^^^^^^^^^^^^

Compilation aborted.

O:\ante\ante-master\bin>

```
which is strange (to what one expected).

**Comment by jfecher** [comment]
Yes it is,  although x1-4 are of type u8, the integer literal is of type i32 (as are all intlits now) by default and thus widens the others in the calculation.

In the future I will probably change Intlits to a new type Int that takes either the size of its operand when used in calculation or the smallest size that can hold it if not.

**Comment by jfecher** [comment]
For your first point, C extends the u8 to an i32 whenever it is used in expressions then truncates only at the very end before the store.  I will probably change the default to something like that.

**Comment by PavelVozenilek** [comment]
Here's what I think about this problem:

There are 2 separate use cases:

1. Mathematical corectness über alles. There's place for no wraparounds. x + 1 > x is always true.
2. Wraparound/truncation is expected and desired: computing hashes, cryptography, interfacing with the HW.

These two cases should be visually separated in code and there should be no undefined behaviour like in C.

What I suggest:

For use case 1:  automatically lift up all operands to 64 bits (its 2017, after all), truncate only the final result. If overflow happens even with 64 bits then jump to slow path calculating the result with infinite numbers.  This slow code could be (hopefully) moved somewhere in far distance from normal path so it woudn't have impact on instruction cache.

The compiler is free to omit checking (or lifting small numbers up) if it can be proved it is not needed. This should include `for (i = 0; i < 10)` type of loops.

Haskell (and IIRC OCaml), for example, use by default infinite precision integer type. This is IMO way too much.


For use case 2:  use something like

```
@{
  ... calculations which need base 2 math
  ... calculations
}

```
to show the desire for traditional behaviour.
For individual operations:

```
c = a @+ b

for (unsigned i = n; i < n; @--i)
```

Numbers could be declared wanting this - then operations on them would not need `@` annotation:

```
var @u32  num1
var @u32 num2

num1 = num1 + num2  // uses wraparound model
num1 = num1 @+ num2 // equivalent

```

**Comment by PavelVozenilek** [comment]
Now, thinking more, my previous suggestion wouldn't be able to deal with complex expressions like:

`res = a / b + foo()/bar()
`

What may work better:

1. The traditional model (with wraparounds) by default. Lifting numbers used in expression up to 64 bits by default (unless it could be optimised away), to eliminate most of unexpected suprises, but no more.  

Operations prefixed with @ would avoid the lifting up:

```
var u8 a = 200
var u8 b = 200
var u8 c = 200
var u8 c = (a @* b) @/c  // will do (u8 * u8) / u8, no automatic expansion to 64 bits
```

Wraparound would be well defined even for signed integers, not as in C.


2. When no compromise corectness is required: use universal infinite Integer type. Expression with at least one Integer will lift the rest up to Integer too and will truncate only the result (if Integer is not also the result).

3. Do not try to solve things like:

`res = a + b + foo()
`
with truncation possibly occuring _inside_ the foo() and thus affecting the whole result. One should use Integer if this is a problem.

4. Make it really, really easy to create generics for handling numerals, e.g.:

```
fun foo: i32|Integer a, u32|i32|Integer b -> i64|Integer

fun bar: T = i32|Integer a, T b) -> T
```

5. Allow to disable Integer type per project. If I do not care I do not want to see it. Functions with only Integer parameter will "disappear" or will result in compiler error, functions which take Integer as one of the options will quietly drop it.

**Comment by jfecher** [comment]
I feel like the best option would be to widen by default, like C does.  Those seeking a true mathematical integer can use a separate type like `Int` (name not final).

  I feel like creating an entire new set of operators for no-widenings may be a bit overkill for a situation that imo is uncommon.  I would rather leave it to an external library than implement it directly.

**Comment by PavelVozenilek** [comment]
At least there should be no undefined behaviour as in C.

**Comment by jfecher** [comment]
Yes, implementation defined if anything but I would rather avoid completely undefined
