### ISSUE TITLE
[tiny feature] if++

### ISSUE THREAD

**Issue by PavelVozenilek** [jfecher/ante#21]
Gcc and clang (and I guess LLVM bitcode too) support hint `__builtin_expect` to the compiler. The hint is usually wrapped within macros:

```
if (likely(..)) { ... }
if (unlikely(...)) { ... }

```
and it has some minor impact:
http://blog.man7.org/2012/10/how-much-do-builtinexpect-likely-and.html

Why not support such featurette directly in the language? E.g.

```
if+ x > y then ... // here we expect the condition to be true most of the time
if- x > y then ... // we expect almost never go this way
if x > y then ...  // no idea or random chance
```
The feature may also serve as very succint documentation, this could be arguably the most useful function. 

If Ante will ever have profile guided instrumentation it may detect clearly mistaken hints and show warning to the user, that his expectations were wrong.

`elif` may use this trick too.  `if-x` would be compiler error.

**Comment by jfecher** [comment]
I think this is too minor a feature to warrant implementing as a first class feature.  I would rather leave this sort of thing to libraries.  There are plenty of features to be worked on instead before version 1.0 is released.

**Comment by PavelVozenilek** [comment]
Libraries are those `likely` and `unlikely `macros, and they are bit clumsy to use (I do write them, mainly as documentation hint).

**Comment by PavelVozenilek** [comment]
If someone doesn't like this feature, or thinks it only adds complexity: it could be disabled per-project. 

stdlib (and 3pp) sources could be then "preprocessed" and if+/if- converted into classical ifs.
