### ISSUE TITLE
delayed but safe initialization of var

### ISSUE THREAD

**Issue by PavelVozenilek** [jfecher/ante#22]
This currently fails:

```
var foo
if 2 > 1 then 
  foo = 0i8
else
  foo = 1i8
```

Will this be eventually supported?

**Comment by jfecher** [comment]
No, that should be a parse error.  Var inferences the variables type based on the expression after the '='.  The correct way of doing this would be

```
var foo =
    if 2 > 1 then
        0i8
    else
        0i8
```

Most of the newlines can be omitted as well.

**Comment by PavelVozenilek** [comment]
Is there a way to use complex block of code to do the initialisation? Something as:

```
var foo =
  {  
     var x = ...
     if ...
     var y = ...
     x + y // this last expression value will be assigned to foo
  }
```

**Comment by jfecher** [comment]
Yes, just indent the block of code:
```
var foo =
     var x = ...
     if ...
     var y = ...
     x + y // this last expression value will be assigned to foo
```

**Comment by PavelVozenilek** [comment]
This quite a feature! Will it be possible to initialize more than one variable this way? I tried and the compiler complains.

```
var foo, bar = 
     ...
     x, y

```

This would also allow to "untie" multiple results from a function, if it will be ever supported.

```
var foo, err = baz()
 if err then ...
```

**Comment by jfecher** [comment]
Yes, `var` and `let` accept patterns as arguments, although it is not currently implemented.  Using patterns, your examples would look like the following:

```
var (foo, bar) = 
     ...
     (x, y)
```

```
var (foo, err) = baz()
 if err then ...
```

**Comment by PavelVozenilek** [comment]
Would it be possible to somehow mix vars and lets?

```
(var foo, let bar) =
   ...
   (x, y)
```


Functions may also support overloading on how many returned values are requested, say:

```
var foo = bar()  // only one returned value is requested - simplest version of bar()
var (foo, err) = bar()
var (foo, err, error_details) = bar(); // bar() which does "everything"
```

Here `error_details` would be calculated only when actually needed. During debugging one would not need to step through code that is not used.

**Comment by jfecher** [comment]
I've never really thought of that before, but I think Ante can reasonably support it using modifiers:

```
var (foo, const bar) =
   ...
   (x, y)
```

As for your second idea I think that can be better solved just by creating a separate function.

**Comment by jfecher** [comment]
An alternative syntax:
```
let (mut foo, bar) =
   ...
   (x, y)
```

**Comment by PavelVozenilek** [comment]
> As for your second idea I think that can be better solved just by creating a separate function.

The implementation would be (most likely) separate functions:
```
fun foo -> i32 = ...
fun foo -> i32, i32 = ...
```

The problem is, w/o such overloading one would need to invent a new name for the second function. This is nuissance usually resulting in great names as `foo2`.

IMHO almost anything what reduces the need to generate a new name is worth the effort.

**Comment by jfecher** [comment]
That is what I meant when I said new function, one with a separate name.  Two functions that do different things should not have the same names.
