### ISSUE TITLE
format of numbers

### ISSUE THREAD

**Issue by PavelVozenilek** [jfecher/ante#23]
Currently underscore is supported as visual separator of digits.

I remember that in some language (I forgot which one) they use ' (single quote) for this exact purpose.

Perhaps this could be per-project option. Default could be underscore, and in project configuration one could remove it or other separator(s).

If the model of "preprocessing" sources according to requested style is adopted then separators in stdlib could be "fixed" too.

In theory it would be also possible to fix number formatting according to culture, say from 1,2 to 1.2.

**Comment by jfecher** [comment]
There is no preprocessing phase, so this would not be possible.
