### ISSUE TITLE
name could bear some semantic meaning

### ISSUE THREAD

**Issue by PavelVozenilek** [jfecher/ante#24]
Currently name is just a text and what characters it contains doesn't matter to the compiler, as long as they are from valid range.

How about possibility, to specify in project configuration that certain format of names implies certain property of its bearer.

Few examples:

* if name ends with ? it is bool variable or function returning bool. Spaniards may want ¿ at the beginning and ? at the end.

* if function name ends with ! then it means the function has no side effects

* if someting is a macro it may start with #

* private names start with lowercase, public with uppercase (ala Go).

stdlib and 3pp sources may get preprocessed and characters not specified in project config preprocessed out, lowercase/uppercase replaced by pub/priv, etc.

These things, rules of formatting and naming, may sound trivial, but they are often contentious and deter people from reusing other's code, "because ugly and nonconforming".

**Comment by jfecher** [comment]
that would mean allowing ! and ? at the end of identifiers.  The rest can be done in a library and does not need a first-class feature for (the name checking step can be done at compile time by a library).  The checking part is already within the planned features, so your fourth point would already be possible.
