### ISSUE TITLE
link error for "hello world" test program

### ISSUE THREAD

**Issue by sparrisable** [jfecher/ante#27]
I am not sure on if this is an error or if I am doing something wrong:
$ cat test.an
print "Hello World!"

$ ./ante_x86_64_unix -r test.an 
/usr/bin/ld: test.o: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
sh: 1: ./test: not found

ubuntu 16.10
$ ldd ante_x86_64_unix 
	linux-vdso.so.1 =>  (0x00007ffe3e717000)
	libLLVM-4.0.so => /usr/lib/x86_64-linux-gnu/libLLVM-4.0.so (0x00007f9a9ce38000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f9a9cab0000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f9a9c7a7000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f9a9c590000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f9a9c1c9000)
	libffi.so.6 => /usr/lib/x86_64-linux-gnu/libffi.so.6 (0x00007f9a9bfbf000)
	libedit.so.2 => /usr/lib/x86_64-linux-gnu/libedit.so.2 (0x00007f9a9bd87000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f9a9bb83000)
	libtinfo.so.5 => /lib/x86_64-linux-gnu/libtinfo.so.5 (0x00007f9a9b95a000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f9a9b73c000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f9a9b522000)
	/lib64/ld-linux-x86-64.so.2 (0x00005607270ed000)
	libbsd.so.0 => /lib/x86_64-linux-gnu/libbsd.so.0 (0x00007f9a9b30b000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f9a9b103000)

Thank you for making ante public for the public to experiment with, to me it looks like a really interesting combination of memory efficiency and clean and expressive syntax.

**Comment by jfecher** [comment]
From a quick glance it looks like you may not have llvm4.0 installed and it is complaining it cant link the shared library.  You can check the llvm version with `lli -version`

If that doesn't work you can try compiling from source in the meantime, there are instructions at the bottom of the README, it should be as simple as cloning the repo and typing `make` to build.

**Comment by jfecher** [comment]
Ok, I've updated the release with a statically linked binary.

**Comment by sparrisable** [comment]
Just for future reference:
On Ubuntu 16.04 llvm version 4 installs lli as lli-4.0, but after doing a symbolic link:
$ sudo ln -s /usr/bin/lli-4.0 /usr/bin/lli

then lli version is correct:
lli --version
LLVM (http://llvm.org/):
  LLVM version 4.0.0

But I still get:

./ante_x86_64_unix -r test.an 
/usr/bin/ld: test.o: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
sh: 1: ./test: not found

I tried to compile ante from source but got:
sudo apt-get install bison
.../ante$ make
Generating parser...
Compiling obj/ante.o...
In file included from src/ante.cpp:3:0:
include/compiler.h:5:39: fatal error: llvm/IR/LegacyPassManager.h: No such file or directory
 #include <llvm/IR/LegacyPassManager.h>
                                       ^
compilation terminated.
Makefile:64: recipe for target 'obj/ante.o' failed
make: *** [obj/ante.o] Error 1

The missing header file is present in packge llvm-3.9-dev:
/usr/include/llvm-3.9/llvm/IR/LegacyPassManager.h 	llvm-3.9-dev

But it does not seems to be present in llvm-4.0-dev.

**Comment by jfecher** [comment]
Yes, llvm-config on ubuntu needs to be the 4.0 version for that reason.  Use `which llvm-config` to figure out which version it is using and move the llvm-config-4.0 file to llvm-config in your bin and check to make sure it is the one being used.

I will change the makefile so this is not necessary in the future.  You should also be able to use the new release's binary, it has been updated.

**Comment by sparrisable** [comment]
Thanks, I tried the new ante binary but ante needs libncursesw.so.6 which is missing on ubuntu 16.04.
As far as I can tell ubuntu 16.04 provides libncursesw.so.5.9.

I will try to compile from source later.

**Comment by sparrisable** [comment]
I tried moving llvm and compilation goes further, but I get errors during linking. Probably some mistake with my llvm setup.
Thanks for your help, I will follow further developments of Ante.

**Comment by jfecher** [comment]
If you reinstall/move back llvm-4.0 to its original position and make sure you pull to the newest commit it should work, it should detect llvm-4.0 and use that over the llvm package if you have it installed.  Try reinstalling llvm-4.0 and building the latest version.

I appreciate your interest in this project, can I ask how you found out about it?

**Comment by sparrisable** [comment]
No problem, I found it at the "Fledgling Languages List": http://fll.presidentbeef.com/
I was looking out for new systems programming languages and liked the syntax and the promising language features (like compile time functions, possibility for rust like memory ownership etc) combined with the exposure of the compile-time API to the language user.

**Comment by sparrisable** [comment]
The latest source compiles for me without problems on ubuntu 16.04, thanks.

**Comment by sparrisable** [comment]
An update, if someone else gets the same error.

I update to the latest git and got the following error when compiling a test program:

/usr/bin/ld: ante.o: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status

To solve this on in my environment, I needed to change the target.h and recompile the ante compiler:

#ifndef AN_LINKER
// This was "gcc" before
#  define AN_LINKER "clang" 
#endif

I am not sure on why gcc and clang differ in this regard or if there is any disadvantage to use clang instead of gcc (since clang was replaced with gcc in the repository)
