### ISSUE TITLE
Building instructions for Windows

### ISSUE THREAD

**Issue by PavelVozenilek** [jfecher/ante#29]
Could you please write down how do you build the Windows version? I may try to make it working under MSVC. Should this succeed it would allow me to use the debugger and, perhaps get some understanding of the code.

**Comment by jfecher** [comment]
Note that the instructions below are only for building the most recent commit that updated the windows version to llvm 4.0

The majority of steps are for building llvm:

1.  Build llvm using these instructions http://llvm.org/docs/GettingStartedVS.html
    - Make sure you have [CMake](www.cmake.org) and [GnuWin32](http://gnuwin32.sourceforge.net/) installed.  The binaries from GnuWin32 should be in your PATH as well.
    -  When you get to the CMake step in the link above if CMake complains it cannot find a CMAKE_C_COMPILER or CMAKE_CXX_COMPILER then make sure you have visual studio and visual studio c++ redistributable installed.  The later should be installed upon creating a fresh c++ project in visual studio.  If after verifying these are installed cmake still gives the same error message open powershell and cd to the directory you extracted llvm to.  Execute cmake with ```cmake .``` and it should build properly.

2.  Open the directory llvm was installed to.  If installing using the CMake GUI it will be the directory you specified, if installed through the CLI, it will be the same directory as the source.  Open the visual studio solution file and build the ```ALL_BUILD``` project in debug configuration.  Then, build the ```INSTALL`` project to install to Program Files (x86) by default.  Congratulations, you installed llvm on windows!

Building Ante:

3.  Download the most recent release as a zip and setup a visual studio project with each source file (in the src directory) and each include file (in the include directory).

4.  To build the parser and output the correct files open powershell and cd to Ante's root directory.  Build the parser with ```bison Lc++ -o 'src/parser.cpp' --defines=include/yyparser.h src/syntax.y```.  This will create several files in the ```src``` directory.  Move the generated headers to the correct directory with ```mv src/*.hh include```.
    - If you plan on changing Ante's syntax by editing syntax.y you should set the above as a custom build step in VS to run before the Build and Rebuild steps.

5. The function ```f32_from_f16``` is bootstrapped in the compiler.  To link correctly, the easiest way is to replace the function stub ```extern "C" float f32_from_f16(float f);``` (in src/operator.cpp) with ```extern "C" float f32_from_f16(float f){ return f; }```

6. Under project settings, add the C:\\llvm-download-directory\include under the C++ include directories.  Under the linker tab, add every installed llvm library found in C:\\Program Files (x86)\LLVM\lib

7.  Build

8.  When testing, using powershell would be the quickest way to test multiple files (test files can be found in the ```tests``` directory).  If you want to test in visual studio without the console window closing, you should test a command similar to ```ante -r filename.an -e``` to open the REPL after filename.an is compiled and run.

**Comment by PavelVozenilek** [comment]
Is building of LLVM really necessary? Do you think there is any chance to try a prebuilt binary?

**Comment by jfecher** [comment]
It is necessary, the llvm binaries do not include the headers for VS to reference nor does it include the library files to link with.

**Comment by jfecher** [comment]
Closing this since with the compiler rewrite these instructions are now outdated, and there are new instructions for windows in the README.
