### ISSUE TITLE
Segfault on type-parameter compile

### ISSUE THREAD

**Issue by ivanbakel** [jfecher/ante#34]
Maybe I'm misunderstanding some basic syntax here

    type Box<'t> = 't contents
    printf "%d" (Box 1u8).contents

This program segfaults at `compFnCall` line 1001, apparently because `val` is `NULL` on a `TypedValue`.

Interestingly, this doesn't happen if you leave out the `printf` - just `(Box 1u8).contents` compiles fine. Could this be an issue with the type inference?

**Comment by jfecher** [comment]
Looks like an issue with binding a generic type with implicit parameters.  If we were to make the cast explicit it would look like:

```
type Box<'t> = 't contents
printf "%d" (Box<u8> 1u8).contents
```

Once this is changed, it is apparent there is another error: extracting the field contents leads to an error claiming that the field does not exist.  I don'tt expect either bug to take long to be fixed.  Interestingly, to make this example work, only the .contents needs to be removed.

**Comment by ivanbakel** [comment]
> extracting the field contents leads to an error claiming that the field does not exist.

I've been having this issue as well - it seems like `Box<'t>` is being replaced with a `'t`? I couldn't tell if it was separate from the original problem, though.

**Comment by jfecher** [comment]
Just pushed a commit that should fix the issue, thank you for the bug report.
