### ISSUE TITLE
Type parameters can't specify type parameters

### ISSUE THREAD

**Issue by ivanbakel** [jfecher/ante#36]
This gives a `TypeVarError; lookup for 't not found`

    Box<'t> = 't contents
    BoxedBox<'u> = Box<'u> box

This might be more of a feature request than a bug.

**Comment by jfecher** [comment]
No, this would be the proper way to ensure the generic type of Box matches BoxedBox.  Its a bug.

**Comment by jfecher** [comment]
Just tried this with the box holding a pointer instead of the element directly:

```
Box<'t> = 't* contents
BoxedBox<'u> = Box<'u> box

let b = BoxedBox Box(new 1u8)
Ante.debug b
```
Oddly enough, it outputs the correct result type of BoxedBox<u8>
