### ISSUE TITLE
Error when compiling tests/list.an

### ISSUE THREAD

**Issue by jfecher** [jfecher/ante#38]
```
tests/list.an: 10,5     error: If condition's then expr's type List<'t> does not match the else expr's type List<i32>
    if l.next != void* 0 then
    ^
```
Type mismatch in the if expression that looks to be caused by failure to bind a generic return type in some contexts.

**Comment by ivanbakel** [comment]
To update this:

The error message on the latest version of master is

    23,12-17 error: Invalid type cast i32 -> List
    var head = List 0

A little bit of debugger diving got me to the point where the type system attempts to compare the type variable of `List` with the tuple wrapper of `i32`, and the result of `getBindingFor` gives a strange-looking `TypeNode` which takes its type name from the name of the `elem` variable.
