### ISSUE TITLE
Correct way to pattern-match two-variable union?

### ISSUE THREAD

**Issue by ivanbakel** [jfecher/ante#39]
I'm testing out pattern matching on tags, and the following code gives me an error:

    type MaybeIntStr =
        | Some u8, Str
        | None

    fun printmis : MaybeIntStr m
        match m with
        | Some i string -> printf "%d and %s" i string
        | None -> print "None"

    let s = Some(1u8, "test")

    printmis(s)

I can't replace `i string` with `i, string` without syntax errors, but trying to compile this as is gives the error `pattern typecast's rval is not a identifier`. My own debugging seemed to suggest that the compiler was taking `i string` as a single variable name instead of splitting it up. What should I be doing?

**Comment by jfecher** [comment]
Pattern matching is in a very early state right now, you would have to use just a normal typecast pattern like `Type val` in this case it would be `Some t` where t would then be bound to the tuple of (u8, Str).  To access each member you can use the # operator as you would with an array:
```
| Some tup -> printf "%d and %s" (tup#0) (tup#1)
```

**Comment by ivanbakel** [comment]
Alright, I'll close this and open a new issue for a different bug I found testing this.
