### ISSUE TITLE
obj/parser.d: No such file or directory

### ISSUE THREAD

**Issue by catb0t** [jfecher/ante#4]
```
ante (master??!)  $ make
Generating parser...
In file included from include/parser.h:8:0,
                 from include/ptree.h:4,
                 from src/syntax.y:8:
include/compiler.h: In member function ‘int DataType::getFieldIndex(std::__cxx11::string&)’:
include/compiler.h:56:26: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         for(int i = 0; i < fields.size(); i++)
                          ^
src/parser.cpp: At global scope:
src/parser.cpp:4734:1: fatal error: opening dependency file obj/parser.d: No such file or directory
 } // yy
 ^
compilation terminated.
Makefile:43: recipe for target 'obj/parser.o' failed
make: *** [obj/parser.o] Error 1
```

system:

```
Linux mint-kitty 4.4.0-23-generic #41-Ubuntu SMP Mon May 16 23:04:25 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by jfecher** [comment]
This is an issue with the current makefile when looking for files, for now you can re-compile it with make again and that should fix it.

**Comment by jfecher** [comment]
I pushed a potential fix that should at least fix the warning if nothing else.  What compiler are you using, and what version?  What does `$CXX -v` output for you?

**Comment by jfecher** [comment]
Also, make sure you have llvm version >= 3.6.0 installed

**Comment by catb0t** [comment]
`$CXX` is `gcc version 5.3.1 20160413 (Ubuntu 5.3.1-14ubuntu2.1)` (G++). Clang is `3.8.0`, but I'm not sure how to check LLVM's version.

**Comment by jfecher** [comment]
`lli --version` should work for llvm

**Comment by catb0t** [comment]
```
LLVM (http://llvm.org/):
  LLVM version 3.8.0
  
  Optimized build.
  Built Apr 21 2016 (14:10:42).
  Default target: x86_64-pc-linux-gnu
  Host CPU: sandybridge
```

**Comment by jfecher** [comment]
Odd, I couldn't replicate this in a linux mint vm.  What does the file directory look like?  How many times have you tried this, and what happens if you try manually creating the file with `g++ -MMD -MP -Iinclude -c src/parser.cpp -MF obj/parser.d -o obj/parser.o` (while in the project's root directory)

**Comment by catb0t** [comment]
```
ante (master??!) $ g++ -std=c++11 -MMD -MP -Iinclude -c src/parser.cpp -MF obj/parser.d -o obj/parser.o                                                                                                
src/parser.cpp:4734:1: fatal error: opening dependency file obj/parser.d: No such file or directory
 } // yy
 ^
compilation terminated.

ante (master??!)  $ tree .
.
├── include
│   ├── compiler.h
│   ├── lexer.h
│   ├── parser.h
│   ├── ptree.h
│   ├── tokens.h
│   └── yyparser.h
├── LICENSE
├── Makefile
├── README.md
├── src
│   ├── ante.cpp
│   ├── compiler.cpp
│   ├── lexer.cpp
│   ├── nodeprinter.cpp
│   ├── operator.cpp
│   ├── parser.cpp
│   ├── prelude.an
│   ├── ptree.cpp
│   ├── syntax.y
│   └── types.cpp
└── tests
    ├── arrays.an
    ├── casting.an
    ├── closures.an
    ├── compilerr.an
    ├── dataDecl.an
    ├── elif.an
    ├── exprblock.an
    ├── fib.an
    ├── floats.an
    ├── fnDecl.an
    ├── functional.an
    ├── language.an
    ├── lazycompile.an
    ├── letbindings.an
    ├── lexerr.an
    ├── math.an
    ├── multiVarDecl.an
    ├── opPrec.an
    ├── polymorphism.an
    ├── pow.an
    ├── printConst.an
    ├── ptr.an
    ├── range.an
    ├── recursion.an
    ├── stdlib.an
    ├── strings.an
    ├── syntaxerr.an
    ├── tuples.an
    ├── typesuffix.an
    ├── varDecl.an
    ├── where.an
    └── while.an

3 directories, 51 files
```

**Comment by catb0t** [comment]
I have tried over and over; it does not work any better. At least 10 times.

**Comment by jfecher** [comment]
Can you try it again with the newest version?  Just wipe the directory and do another git clone; There was a problem a few days ago that the make file did not create the obj folder if it did not exist already, so can you see if that works?  And try the manual creation of the file too.  Sorry for putting you through all this, I just can't seem to replicate it myself.  I'm not sure if it is a gcc thing or not, although 5.3.1 is not the newest version, it _should_ be able to handle -MMD properly.

**Comment by jfecher** [comment]
Ok, I was just able to reproduce it, it seems I was right when I suspected it was the old makefile problem with the obj directory not being made.  Just update to the newest version and it should compile.
