### ISSUE TITLE
[stdlib]Why the type of string's length is u32?

### ISSUE THREAD

**Issue by codehz** [jfecher/ante#46]
https://github.com/jfecher/ante/blob/master/stdlib/prelude.an#L46
I think it should be usz...

**Comment by jfecher** [comment]
u32 can store a string up to 2^32-1 characters in length, using 4 GiB of memory.  `usz` may be better for embedded platforms, but would also increase the size of every Str on 64-bit platforms.

**Comment by codehz** [comment]
@jfecher It is generally assumed that the length type should be consistent with the pointer.
