### ISSUE TITLE
Should have its own organization on github

### ISSUE THREAD

**Issue by Elronnd** [jfecher/ante#47]
I think there should be an "ante" organization, where this repo is moved and then that the stdlib be moved to its own repo.

**Comment by jfecher** [comment]
The project as is isn't anywhere close in scale that would merit a github organization.  Unless there is a sudden uptake of interest in the project it is likely to be just me for a while.  I can always move it to an organization page later if the project proves to have enough support.

**Comment by Elronnd** [comment]
Alrightly, cool.  Unrelated, but is there a tutorial, or a guide, or some example code somewhere?  The project looks interesting, but I have no idea where to start!

**Comment by jfecher** [comment]
The best place to go for the most up to date code examples is the `tests` directory of the master branch.  Each of these (except for tests/list.an atm) are guaranteed to work as they are used to test the compiler itself.  If you want a more tutorial-style guide, there is `tests/old/language.an` which was written to cover the language's feature in that kind of a style, although it is somewhat outdated.  Lastly, there is also ivanbakal's (branch)[https://github.com/ivanbakel/ante/blob/documentation/doc/] where he is working on describing the language (currently limited to the type system).
