### ISSUE TITLE
Use editline or readline for the repl

### ISSUE THREAD

**Issue by Elronnd** [jfecher/ante#51]
It would be nice if the repl used editline or readline or something like that so there could be history search and left/right arrows.  I can make a pr if you're interested.

**Comment by jfecher** [comment]
The problem with those is that I believe you cannot intercept the output to colorize it (correct me if I'm wrong).

I have not been focusing on the repl yet until every expression can be properly evaluated compile time and you can get more useful output, but once that is done I hope include syntax highlighting in the repl itself.

**Comment by Elronnd** [comment]
Oh, hmmm.  I'm pretty sure you can, by sending ansi control codes, but not on the fly.  Maybe a homegrown solution for history/cursor movement then?

**Comment by jfecher** [comment]
Yes, I had a similar solution in a previous interpreter i made where i just rolled out my own history and escape-sequence detection just so i could have syntax highlighting.  Its reinventimg the wheel but it removes a dependency and adds a shiny coat of paint to the wheel.
