### ISSUE TITLE
Adding docker file

### ISSUE THREAD

**Issue by codec-abc** [jfecher/ante#56]
Hi,

What do you think of adding a dockerfile to easily get a working environment easily for most users? Also it probably can be used to have a some point a online playground.

**Comment by jfecher** [comment]
I think this would be a good idea, although I do not have any experience with docker containers currently.  I would like to setup a working repl on the website eventually.

**Comment by codec-abc** [comment]
Ok then I will try to make the dockerfile (it should be pretty easy giving the small set of dependencies).

**Comment by codec-abc** [comment]
OK I made some progress and managed to create a Dockerfile to create an environment to get Ante running in it.

```Dockerfile
FROM ubuntu

RUN apt-get update && \
    apt-get -y install software-properties-common && \
    add-apt-repository -y ppa:ubuntu-toolchain-r/test && \
    apt-get update && \
    apt-get -y install g++-7 gcc-7 llvm-5.0 llvm-5.0-dev wget git make bison && \
    export CC='gcc-7' && \ 
    export CXX='g++-7' && \
    wget -O - http://apt.llvm.org/llvm-snapshot.gpg.key| apt-key add - && \
    apt-get autoremove llvm clang && \
    rm -rf /usr/include/llvm && \
    rm -rf /usr/include/llvm-c && \
    update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 60 && \
    update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 60 && \
    mkdir /home/ante && \
    git clone https://github.com/jfecher/ante.git /home/ante && \
    cd /home/ante && \
    make
```

Building the image with

```
docker build . -t ante
```

Then launching it in interactive mode with 
```
docker run -it ante
```

Allow me to compile and run a unit test. For example

```
/home/ante/ante /home/ante/tests/integration/fib.an
/home/ante/tests/integration/fib
```

prints

```
fib(3) = 2
fib(4) = 3
fib(5) = 5
fib(6) = 8
fib(7) = 13
fib(30) = 832040
fib(46) = 1836311903
fib(47) = -1323752223
fib(48) = 512559680
```

It may be enough for users to try out Ante easily (especially those on Windows).

**Comment by jfecher** [comment]
Tested this with make test and all tests pass.  Unfortunately the current master
branch has a rather broken repl.

If you submit a pull request with a change to the readme I will add it to the repo.  I
may consider adding vim and ante's vim plugin to the Dockerfile as well in the future
since there is not vi/vim/nano installed by default.

**Comment by codec-abc** [comment]
For the vi/vim/nano thing I don't know if it is a "good thing" to have them in the docker container. Usually I try to keep the container as slick as possible (But I am by no means a docker expert). Usually when I try a language in a container I share some volume from my host and put my source code in there which give 2 advantages:

1. I can edit them with the editor of my choice (usually vscode).
2. I don't lose them if I destroy the container.

I will do the PR with the readme right away.

**Comment by codec-abc** [comment]
Hi, I have done some experimentation forward with the docker file. By slighting modifying it, I was able to build a web server that compile code on the fly using a web page by using [this project](https://github.com/jondgoodwin/conesite) as a base. The server is just a dotnet core application that spawn a Docker container and give the container the code through the command line encoded as base64. Then the server wait a few seconds for the container to run the compiler and spit out the compiler error message or the result of the execution if the compilation succeeded. I did this only to play around docker and to see how to pipe stuff between the host and the container. It is a bit messy but if for some reason you want to experiment with it you only need a environment where docker and dotnet core are installed. Then, build the dockerfile with the command `docker build . -t ante` then start the server by typing these commands `dotnet restore && dotnet build && dotnet run`.

**Comment by codec-abc** [comment]
Of course, I forget to put a link to the repository. [Here we go](https://github.com/codec-abc/ante-live-compiler)

**Comment by jfecher** [comment]
Thank you for this.  I tried to set it up myself but it looks like it requires 'Microsoft.AspNetCore.App' version '2.1.0-rc1-final which was not found with the latest build of dotnet-sdk-rc.

**Comment by codec-abc** [comment]
I updated the repository to hopefully fix it. If it does not work maybe you can try to create a new asp project from scratch and see what version of AspNetCore.App it uses (in the csproj) by using the command `dotnet new webapi`. Then by using the command above you can check to see if you are able to run this new project (and maybe troubleshoot it).

**Comment by jfecher** [comment]
my `dotnet --version` prints `2.1.300-rc1-008673`.  The stable version for my distro is only `2.1.200`.  I am also testing on linux so it is possible that not all packages are available or updated.  It seems to find the correct version 2.1.0 when buliding but cannot find it when running.

**Comment by codec-abc** [comment]
Maybe you can try a manual installation by uninstalling your current version and using [this link](https://www.microsoft.com/net/download/thank-you/dotnet-sdk-2.1.300-linux-x64-binaries) and [maybe this one](https://www.microsoft.com/net/download/thank-you/dotnet-runtime-2.1.0-linux-x64-binaries) since it appears that your current installation is broken since it is not able to run a project created from scratch.

**Comment by jfecher** [comment]
I am able to get the server running with that version, thank you
