### ISSUE TITLE
Segfault

### ISSUE THREAD

**Issue by Elronnd** [jfecher/ante#58]
The compiler segfaults with this code:

    fun hex: Str str -> i32                                                                                                            
        mut ret: i32 = 0
        mut i: usz = 0

        while i < str.len do
            ret *= 16
            ret += match str#i with
            | '0' .. '9' -> str#i - '0'
            | 'a' .. 'f' -> str#i - 'a'
            | 'A' .. 'F' -> str#i - 'A'
 
            i += 1
        ret

    let a = hex "04"

**Comment by jfecher** [comment]
This is most likely from the range patterns used in the match expressions, they are not implemented yet.  That being said they also should not segfault.  I tested this with my local version (on the jit branch) and it is already fixed there.  I think I will hold off on this fix until jit is merged into master.
