### ISSUE TITLE
New parameter syntax

### ISSUE THREAD

**Issue by jfecher** [jfecher/ante#59]
For a while now Ante has had the function declaration syntax:

```
fun name: Type1 param1, Type2 param2 -> ReturnType
```

The `Type1 param1` syntax allows things like the shorthand `Type1 param1 param2 param3` for multiple parameters of the same type but notably goes against the mostly standard `param: Type` syntax most languages use.  For consistency, this also means that type declarations must use the `Type value` pattern as well which can be visually confusing for larger types.

There are several possible alternatives.

1. Use a variant of ML's `let name (param1: Type1) (param2: Type2): ReturnType` syntax.
    - This syntax has the benefit of somewhat mimicking the syntax of a function call but this falls apart when the parameter types are required.  This also requires a lot of unnecessary noise in the form of parenthesis and a colon for every parameter which increases the size of a function's header, making it less likely a long function can fit in a given column limit.
    - Loses ability to have the parameter shorthand syntax

2. Use a variant of Haskell's
```
name :: Type1 -> Type2 -> ReturnType
name param1 param2 = ...
```

   - - Requires 2 lines.  This can be a negative or positive.  On one hand it requires less columns so longer declarations need to be wrapped less often and makes the function's type available at a glance.  On the other hand  it is more difficult to tell the type of each parameter as quickly.
      - Separating parameter types with `->` makes it more difficult to read for me at least.
      - Loses ability to have the parameter shorthand syntax

3. Use a new syntax, such as `fun name param1 param2: Type1, Type2 -> ReturnType`
    - This syntax resembles a function call even with the added parameter types.
    - The function's type is separate from the function's "form."  This can be a positive or a negative.  On one hand it makes it easier to see the function's type at a glance but on the other it makes it more difficult to see each individual parameter's type, requiring cross referencing and requiring the programmer insert code in two separate spaces when adding a new parameter.
    - The parameter type shorthand can also be used in a slightly modified form, eg: `fun append: Str a b c d -> Str` becomes `fun append a b c d: 4 Str -> Str`
    - Exact same size as current syntax
    - Preserves ability to omit return type for void function or replace with `=` for return type inference.
    - Some function definitions may be harder to read with only spaces separating parameters.
    - Type information can optionally be put on second line, with the `:` being either at the end of the first line or beginning of the second, eg.
```
fun name param1 param2
: Type1, Type2 -> ReturnType
```

For these reasons, syntax 3 is being proposed to replace the current syntax for function declarations.

If this is implemented then it is likely type and variable declarations will be changed to one of:

```ante
type Short = a b c : i32,i32,i32

type Short2 = a b c: 3 i32

type Long =
    a: i32
    b: i32
    c: i32

type LongAlternate =
    a i32
    b i32
    c i32

let vardecl: i32 = 4
```

The Short type declarations do not work as well as the functions do unfortunately.

EDIT: the proposed syntax also allows for operator overloading parameters to be specified infix:

```
fun l = r: Str, Str -> bool

fun vec#index: Vec 't, usz -> 't
```

The types can also potentially be aligned vertically with the parameters for faster identification, though it is somewhat ugly and requires a bit of work:

```
fun draw board       ctxt         time_left:
         ChessBoard, GameContext, Time.Duration -> Image
```

**Comment by arBmind** [comment]
Hey, I found your post on Reddit.

All of your arguments are well considered. I would like to add my following thoughts. Keep in mind, I am no expert.

If you intend your language to be use widely I would suppress the desire to build shortcuts into it right from the start. Using the same types for multiple arguments is a code smell. The exceptions are situations, where the order in inherent or does not matter. And for both you might be better of with an array, span or value pack. So I would leave out the `4 i32` syntax.

Separating the types from the names has the big disadvantage, that your eyes will see only the name or the type. Matching both is a burden on every reader of the function signature. Even for functions with two or three arguments, it will be difficult to associate the type to a name, if the types get more complex.

I would favor a basic syntax and consistent syntax pattern: `fun name a:i32 b:i32 c:i32 -> :i32`. All type expressions start with a colon - which makes the very easy to spot. Commas and Brackets should be allowed to help the programmer write more readable code.

Ante seems to have many similar ideas to the Rebuild Language Project. https://github.com/rebuild-lang - I would be very glad to discuss some ideas with you.

My RLP approach extends the function syntax to support operator / infix syntax, by allowing a left argument as well:
`fn (l1:Type l2:Type2) name r1:Type3 r2:Type4=default -> res1:Type5 res2:Type6`.
* At most one left argument is allowed. The example uses a (tuple) as the left argument.
* The results may be named as well to allow them to be assigned independently.

Keep up the good work!

**Comment by jfecher** [comment]
> My RLP approach extends the function syntax to support operator / infix syntax, by allowing a left argument as well:
> `fn (l1:Type l2:Type2) name r1:Type3 r2:Type4=default -> res1:Type5 res2:Type6.`

How does this differentiate `f g x` where f is a normal function taking two arguments and g is an infix function taking an argument on the left and an argument on the right?

**Comment by arBmind** [comment]
> How does this differentiate f g x where f is a normal function taking two arguments and g is an infix function taking an argument on the left and an argument on the right?

The infix notation requires precedence and association rules. None of the following have been tested against reality. My reasoning tries to favor readable code. You define these rules on a per (infix) function basis.

Infix versus regular functions has some basic rules, that are easy to follow by the reader and the parser.
Example: `f g x`
1. The identifier `f` is parsed. `f` is resolved to a function. To complete the call to `f` the arguments are parsed.
2. The identifier `g` is parsed. `g` is resolved to an infix function. But the left arguments do not match. Therefore an error is produced.

So if you indented to pass `f` to `g` as an left argument, you are required to make this visible to the reader and parser.

**Comment by jfecher** [comment]
I have decided not to change the syntax.
