### ISSUE TITLE
Add support for explicit currying via `_`

### ISSUE THREAD

**Issue by jfecher** [jfecher/ante#66]
When used in a function-call, the `_` marks an explicitly curried parameter since ante does not have implicit currying.

The following:
```hs
foo a _ c
bar _ _ 3
```
Should be equivalent to (_param names are unimportant/placeholders):
```hs
fn _param1 -> foo a _param1 c
fn _param1 _param2 -> bar _param1 _param2 3
```

This should be a relatively easy check to do manually after parsing a `Ast::FunctionCall` in `parser/mod.rs`. After a `_` is found in a function call, the parser can manually desugar it by returning an `Ast::Lambda` containing the function call.

**Comment by thehabbos007** [comment]
I have a quick question about this, how would we handle values starting with an underscore that are not meant to be explicitly curried but passed as args? :)

**Comment by jfecher** [comment]
This would only transform functions that have parameters named `_` and shouldn't affect variables starting with an underscore like `print _foo`. The first is safe because ante doesn't allow a single `_` as a valid variable name - or rather it is valid but you can't reference a variable using it so using it in code is like asserting that it is never used. This means the `_` in  `foo _` is guaranteed never to refer to an existing variable.

The check for not adding a variable named `_` into scope is here: https://github.com/jfecher/ante/blob/master/src/nameresolution/mod.rs#L301-L308

**Comment by thehabbos007** [comment]
Ah so when you write "_param names are unimportant/placeholders" it just refers to them being used for the sake of example, not that they are valid syntax?

**Comment by jfecher** [comment]
Exactly, yes. Inevitably when you desugar it into a lambda you're going to have to choose names for the parameters and I used `_param1` etc in my example. The real names will have to be guaranteed not to conflict with anything in scope. The easiest way to do this would be to prefix them with some character that can't be used in identifiers like `$` or almost any symbol

**Comment by thehabbos007** [comment]
Hope im not asking too many questions, but would you rather have that the arg is modified in-place or replaced when it is an underscore and has to get a new non-colliding name for the lambda?

**Comment by jfecher** [comment]
> Hope im not asking too many questions,

Not at all, I enjoy answering them :)

> would you rather have that the arg is modified in-place or replaced when it is an underscore and has to get a new non-colliding name for the lambda?

If I understand this correctly you're asking when you have `foo _ a` then desugar partially to `fn newname -> foo _ a` should the `_` node be mutated with a `newname` or should you create an entirely new Variable node and replace the whole node with that?
If so, I'd say either would be correct so whichever you think leads to cleaner code. If we're getting pedantic, mutating would save on one allocation but its not clear how big a difference this makes.
