### ISSUE TITLE
Problems Building on Windows 10

### ISSUE THREAD

**Issue by Ivo-Balbaert** [jfecher/ante#69]
Building Ante on Linux or WSL is quite straightforward. 
Building on Windows is another matter, due to the difficulties of compiling LLVM on Windows.

I tried building on a Windows 64-bit machine.

Prerequisites:
(1) Rust
(2) Cygwin:  In the step:  llvmenv build-entry -G VisualStudio -j7 10.0.0                                                                                                                          
   I got an error that "perl was not found" 
   So I installed Perl from cygwin64  from cmake.org using the Windows 64 bit installer

- After this, the first two steps:
                   cargo install llvmenv
                   llvmenv init
went smoothly. But the following step:  llvmenv build-entry -G VisualStudio -j7 10.0.0  
gave a lot of .h header files not found errors.
After changing X86 to X64 in entry.toml in C:\Users\ivoba\AppData\Roaming\llvmenv most of these errors were gone.

- Now the step:  llvmenv build-entry -G VisualStudio -j7 10.0.0
started very promisingly and ran for about 45 min building myriads of cpp files without any trouble.

Then suddenly I stared getting MSB3073  errors :
  l/llvmenv/10.0.0/projects/openmp/runtime/exports/win_32/lib".
C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(138
,5): error MSB3073: The command "setlocal [C:\Users\ivoba\AppData\Local\llvmenv\10.0.0\build\projects\openmp\runtime\sr
c\omp.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(138
,5): error MSB3073: "C:\Program Files\CMake\bin\cmake.exe" -E make_directory C:/Users/ivoba/AppData/Local/llvmenv/10.0.
0/projects/openmp/runtime/exports/common/include [C:\Users\ivoba\AppData\Local\llvmenv\10.0.0\build\projects\openmp\run
time\src\omp.vcxproj]
... this goes on for some pages

Then it seems to resume with:
  Building Custom Rule C:/Users/ivoba/AppData/Local/llvmenv/10.0.0/tools/opt/CMakeLists.txt
  AnalysisWrappers.cpp
  BreakpointPrinter.cpp
  GraphPrinters.cpp
  NewPMDriver.cpp
  PassPrinters.cpp
  PrintSCC.cpp
  opt.cpp
  opt.vcxproj -> C:\Users\ivoba\AppData\Local\llvmenv\10.0.0\build\Release\bin\opt.exe
  Building Custom Rule C:/Users/ivoba/AppData/Local/llvmenv/10.0.0/tools/polly/lib/External/CMakeLists.txt
  isl_test.c
  polly-isl-test.vcxproj -> C:\Users\ivoba\AppData\Local\llvmenv\10.0.0\build\bin\Release\polly-isl-test.exe
  Building Custom Rule C:/Users/ivoba/AppData/Local/llvmenv/10.0.0/tools/sancov/CMakeLists.txt
  sancov.cpp
  sancov.vcxproj -> C:\Users\ivoba\AppData\Local\llvmenv\10.0.0\build\Release\bin\sancov.exe
  Building Custom Rule C:/Users/ivoba/AppData/Local/llvmenv/10.0.0/tools/sanstats/CMakeLists.txt
  sanstats.cpp
  sanstats.vcxproj -> C:\Users\ivoba\AppData\Local\llvmenv\10.0.0\build\Release\bin\sanstats.exe
  Building Custom Rule C:/Users/ivoba/AppData/Local/llvmenv/10.0.0/tools/verify-uselistorder/CMakeLists.txt
  verify-uselistorder.cpp
  verify-uselistorder.vcxproj -> C:\Users\ivoba\AppData\Local\llvmenv\10.0.0\build\Release\bin\verify-uselistorder.exe
  Building Custom Rule C:/Users/ivoba/AppData/Local/llvmenv/10.0.0/utils/yaml-bench/CMakeLists.txt
  YAMLBench.cpp
  yaml-bench.vcxproj -> C:\Users\ivoba\AppData\Local\llvmenv\10.0.0\build\Release\bin\yaml-bench.exe

- But sadly it ended with:

  Building Custom Rule C:/Users/ivoba/AppData/Local/llvmenv/10.0.0/tools/yaml2obj/CMakeLists.txt
  yaml2obj.cpp
  yaml2obj.vcxproj -> C:\Users\ivoba\AppData\Local\llvmenv\10.0.0\build\Release\bin\yaml2obj.exe
**

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: CommandError { errno: 1, cmd: "\"cmake\" \"--build\" \"C:\\\\Users\\\\ivoba\\\\AppData\\\\Local\\\\llvmenv\\\\10.0.0\\\\build\" \"--target\" \"install\" \"--config\" \"Release\"", stdout: None, stderr: None }', C:\Users\ivoba\.cargo\registry\src\github.com-1ecc6299db9ec823\llvmenv-0.3.1\src\bin\llvmenv.rs:163:32
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace 

This is how far I've got, any help is much appreciated.

Another solution might be that an Ante binary release is provided for Windows, as is done by the designers of the Vale and Beef programming languages.

**Comment by jfecher** [comment]
Thanks for bringing this to my attention. Unfortunately, I don't have any quick tips that are likely to fix your compilation. Historically building llvm on windows has been rather inconsistent and ante's previous solution (before the compiler rewrite) was to provide windows binaries as you mentioned. I've been rather busy with some other aspects of my life lately but I'll try to see if I can do some more testing for more consistent build steps on windows. Seeing as how the last binary is now over 3 years old, I'd like to update that too.

**Comment by Ivo-Balbaert** [comment]
Thanks very much! It is not a high priority for me at the moment, I can work with ante on WSL.

Sent from Mail for Windows 10

**Comment by jfecher** [comment]
I added a section on compiling on windows with cmake to the README, let me know if this works for you. I ran into some issues with z3 being required myself and it not recognizing my version but otherwise it seemed to work.

**Comment by Ivo-Balbaert** [comment]
Thanks for your help! This time I got a lot further, all LLVM compilations seem to conclude successfully.
No I get stuck in the last stage when I execute "cargo build" in the ante folder. It hangs when compiling llvm-sys:

       ...
       Fresh clap v2.33.3
       Fresh syn v1.0.64
       Fresh mimalloc v0.1.25
       Fresh goldentests v0.3.7
   Compiling llvm-sys v100.2.1
       Fresh inkwell_internals v0.3.0 (https://github.com/TheDan64/inkwell?branch=master#1c5e323d)
     Running `c:\ante\target\debug\build\llvm-sys-45e41712301e7351\build-script-build`
    Building [=======================>   ] 57/62: llvm-sys(build)
    // hangs forever

No idea what could cause this I'm afraid.

**Comment by Ivo-Balbaert** [comment]
Further info:

Apparently Avast Antivirus caused the blocking, pausing this service, I got this error output amidst a lot of other compiling info:


....

error: linking with `link.exe` failed: exit code: 1120


lib" "advapi32.lib" "ws2_32.lib" "userenv.lib" "msvcrt.lib"
  = note: libinkwell-6371cbbefa4d2c1d.rlib(inkwell-6371cbbefa4d2c1d.inkwell.38g9wbh4-cgu.8.rcgu.o) : error LNK2001: unresolved external symbol LLVMTypeOf
          ante.4tnmk3x1xzr52ecx.rcgu.o : error LNK2001: unresolved external symbol LLVMTypeOf
          libinkwell-6371cbbefa4d2c1d.rlib(inkwell-6371cbbefa4d2c1d.inkwell.38g9wbh4-cgu.12.rcgu.o) : error LNK2001: unresolved external symbol LLVMTypeOf
          libinkwell-6371cbbefa4d2c1d.rlib(inkwell-6371cbbefa4d2c1d.inkwell.38g9wbh4-cgu.5.rcgu.o) : error LNK2001: unresolved external symbol LLVMTypeOf
          libinkwell-6371cbbefa4d2c1d.rlib(inkwell-6371cbbefa4d2c1d.inkwell.38g9wbh4-cgu.10.rcgu.o) : error LNK2001: unresolved external symbol LLVMTypeOf
          ante.4tnmk3x1xzr52ecx.rcgu.o : error LNK2019: unresolved external symbol LLVMGetElementType referenced in function _ZN7inkwell7builder7Builder10build_call17ha7551ba40489ee6cE
          libinkwell-6371cbbefa4d2c1d.rlib(inkwell-6371cbbefa4d2c1d.inkwell.38g9wbh4-cgu.2.rcgu.o) : error LNK2001: unres

...

assembler referenced in function LLVMInitializeAllDisassemblers
          c:\ante\target\debug\deps\ante.exe : fatal error LNK1120: 636 unresolved externals


error: aborting due to previous error

error: could not compile `ante`

Caused by:
  process didn't exit successfully: `rustc --crate-name ante --edition=2018 src\main.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,link -C embed-bitcode=no -C debuginfo=2 -C metadata=1d5c41a41026a2bf --out-dir c:\ante\target\debug\deps -C incremental=c:\ante\target\debug\incremental -L dependency=c:\ante\target\debug\deps --extern clap=c:\ante\target\debug\deps\libclap-4fad1c9d4c2fc85e.rlib --extern colored=c:\ante\target\debug\deps\libcolored-81b6ea05eb8c61e6.rlib --extern difference=c:\ante\target\debug\deps\libdifference-34d3f61c619128ea.rlib --extern dirs=c:\ante\target\debug\deps\libdirs-40becdc048f7772e.rlib --extern goldentests=c:\ante\target\debug\deps\libgoldentests-8a664ec2a167bd5c.rlib --extern inkwell=c:\ante\target\debug\deps\libinkwell-6371cbbefa4d2c1d.rlib --extern mimalloc=c:\ante\target\debug\deps\libmimalloc-f156cb09e570e155.rlib -L native=c:\ante\target\debug\build\llvm-sys-2a311d60236644bf\out -L native=C:\llvm-build\Release\lib -L native=c:\ante\target\debug\build\libmimalloc-sys-e50859419ad8961a\out` (exit code: 1)

Seems somehow the LLVM build didn't work 100%

**Comment by jfecher** [comment]
Closing this issue as ante is now able to be built without llvm via `--no-default-features`, requiring only cranelift as a backend.
In the future, ante still needs to provide easier options for users to build with the llvm backend, and barring any better official windows support from llvm itself, this will likely be in the form of premade binaries for major releases. This would help most users, except for contributors on windows.
