### ISSUE TITLE
[feature] metametaprogramming

### ISSUE THREAD

**Issue by PavelVozenilek** [jfecher/ante#7]
This is feature suggestion based on the first (and shallow) reading of the spec.

Problems which it may solve:
 1. Libraries tend to grow in complexity and became unusable.
 2. Solving naming style (CamelCase, using_underscores, etc) conflicts.
 3. Solving "parenthesis versus significant whitespace" conflict.

Imagine a new project. Developer states (perhaps in a project specification file) that he wants to use parenthesis and `underscored_names` everywhere.  The compiler looks up actually imported files from standard library (and 3rd party libraries), modifies them according to the wish and copies them somewhere into the project directory. Developer then sees only code formatted according to his wishes.

The libraries would need to be written in form that allows automatic conversion. 

-------------
Possibilities for problem 3: Python style, C parenthesis with different styles where to place the brackets, perhaps even Ruby style. 

-----------
Possibilities for problem 2: CamelCase, Ada_Style, underscores_everywhere, possibly also style-with-minuses-as-separators. Case may or may not be made significant. Language keywords may be converted into uppercase.

Syntax should be provided for names which cannot be written in different way for whatever reason, e.g. `!!` prior the name or at the top of library.

The compiler may even enforce use of given style (ala gofmt).

--------------

Problem 1 can be solved this way:

Library writer would announce features which can be selectively enabled, something as:

```
fetaures 
{
  MY_FEATURE1 "short description"
  MY_FEATURE2 "description"
  XYZ "..."
}
```
at the top of the library.  Library code will be filled with something as C conditional compilation:

```
@if(MY_FEATURE2) 
fun xyz : ...
@fi
```

It would be ugly and complex but the end user won't see it (unlike in C/C++). All the hard work and complexity would be on library writer only.

Then the user would specify (perhaps in project configuration file):

`library foo uses features MY_FEATURE1, XYZ, ABC`

and the compiler would preprocess imported libraries and remove all parts that are not needed. Result files will be placed into project directory. Programmer would see only the code he requested, w/o parts he doesn't need and w/o the preprocessor directives.

The `import` directive would stay as it is now. 

3rd party library may request certain feature to be present, e.g. 

`import "foo" needs XYZ`

and if this library is used by the app then the feature must be also specified by the project.

**Comment by jfecher** [comment]
Very interesting ideas.

> CamelCase, Ada_Style, underscores_everywhere, possibly also style-with-minuses-as-separators. Case may or may not be made significant.

This is already possible with the current planned API, except for the kebab-case.  Although the kebab-case would be possible to compile, it would have to have a work around to call them as it is not a valid identifier.

> Possibilities for problem 3: Python style, C parenthesis with different styles where to place the brackets, perhaps even Ruby style. 
...
> Language keywords may be converted into uppercase.

This goes into my last statement a bit.  Although there is a huge focus on meta programming, I want to keep syntactic and semantic analysis separate to keep compilation times quick, so the one major restriction is that modifications to the parser are not currently possible.  I am open to suggestions if you have a method of getting a similar feature without modifications to the parser or a pre-processor.

> The compiler may even enforce use of given style (ala gofmt).

This is also already possible :)

> Library writer would announce features which can be selectively enabled

I like your solution to this.  I think the possible features part could be done with compiler directives, and the only thing that may need to be added is either some syntactic sugar for the importing module, or just mandate it be done with compile-time helper functions.

**Comment by PavelVozenilek** [comment]
I have been inspired by Nim language ( http://nim-lang.org/ ) for the name styles. Nim allows to use any style (even to mix them). Some people love it, some see it as crazy.  It is very emotional thing.  Here it would be completely up to the programmer - from being most restrictive to everything goes.

Similarly the brackets/whitespace. 


Implementation of these features can (probably) be done before any analysis, just like C preprocessor handles it. E.g. preprocessor sees original symbol `TheValue` and converts it blindly into `the_value` and writes it into the file that gets later analysed again (if not already cached). Nonchangeable names forced with `!!` could be handled by the preprocessor too.

The `kebab-case` is IMO the most readable of all. Minus as arithmetic operator could be forced by mandatory space before it. I think Julia language does this.

----------------------

The main advantage of extracting "only what's needed" from the libraries is readability and simplicity of the result. 

Quite often only very small part of provided functionality is needed and people reimplement it by themselves because learning the big library needs more time.

**Comment by jfecher** [comment]
I am just against the notion of adding in a preprocessor in general, it adds too much time and will be rarely used imo

**Comment by PavelVozenilek** [comment]
C preprocessor has (standard mandated) seven passes, and usually it processes the whole world. That's why it is slow.

**Comment by jfecher** [comment]
Yes, but one pass is still slower than zero passes.  I just do not see much of an advantage in adding a preprocessor just to change some basic syntax.  It could be useful in that it could allow for the declaration of new operators though.  I want to try to minimize unnecessary contributions to compilation time.  For reference, the current system used is a single pass _after_ parsing to register each function so they may be declared after they are used, then normal compilation with a JIT compiler that, while slow, _only_ runs when necessary, compared to a preprocessor that would need to run before every program, every file, every module...

**Comment by PavelVozenilek** [comment]
Note that my idea is NOT to preprocess files every time. Library source code would be preprocessed once and the result put into project directory, where it would be kept for later user. Developer would see only this final result.

--------------

C preprocessors gets bad rap but it allows to implement useful things in the most natural way. For example I can write tests like this:

```
#ifdef DEBUG
TEST()
{
  assert(1 + 1 == 2);
}
#endif 
```

because of the preprocessor ( http://www.codeproject.com/Articles/9757/Minimal-unit-test-library-for-C ). No need for functions, no need for classes, no need for separate builds, no abstractions complicating the intent.  

Preprocessor macros (with gotos and labels) also allow to write finite state machines in almost the ideal way.

**Comment by jfecher** [comment]
Ante already has macros, and compiler directives could be used as #ifdef DEBUG ... #endif guards, and most likely finite state machines too but I'm a bit inexperienced with their implementation with c macros, so I could be wrong.

**Comment by PavelVozenilek** [comment]
FSM implementation in C can be seen e.g. here:
https://news.ycombinator.com/item?id=7685271

This variant doesn't require switch and enums or anything even more complicated. Gotos and labels can be hidden by macros (like STATE(A), NEXT_STATE(B) ).

**Comment by jfecher** [comment]
So are you proposing gotos and labels be implemented?  Macros already are so that is a nonissue.

**Comment by PavelVozenilek** [comment]
I am pointing out that in C labels + gotos allow for perfect syntax of certain functionality (FSM). By perfect I mean that there are no unnecessary  constructs (like enums or functions) going in the way. 

There are several very common problems - FSMs, text parsers, error handling, testing, mocking, units (kg versus meters), etc - which could have very natural syntax. Languages too often concentrate on theory (let's make _everything_ object oriented with no exception) and ignore user's pain.


I'll give examples what I would see as ideal syntax:

1. FSM: it would be something like those `STATE(state_name)` and `NEXT_STATE(something)` macros creating their own scope. No other constructs should be needed (and certainly nothing like the Boost::FSM monster).

2. text parsers: something where one directly writes BNF with actions. I.e. no separate tools as yacc, no clumsy workarounds because certain characters are not allowed in certain place in the source.

3. error handling: not needing complicated types because of rare errors. E.g.:

 ```
 double foo(int x) 
 {
   if (x == 0) return :divide_by_zero
    return 1/x
 }

 double res = foo(1)
  if (err) return err
  // or
  // if (err == :divide_by_zero) res = 0.0

  print(res) // error is handled by now, compiler knows it
 ```

 Here function signature is not complicated by error handling, compiler would enforce error checking and handling, all errors would be traced (thus no exceptions secretly flying over ones head).

3. testing:

 ```
 TEST()
 {
   assert(1 + 1 == 2)
 }
 ```

 Tests would be compiled together with the code and invoked automatically at the start.

 A negative example now _not_ to do it is the Pony language ( https://tutorial.ponylang.org/testing/ponytest.html ). To make a new test one needs to create new class, implement several methods and register the class in certain place. So many useless lines, unnecessary coupling, the intent is visually lost in infrastructure garbage. 

4. mocking: easy redefinition of certain functionality in given context. No need to force one to use virtual functions, mocking aware base classes or any other modification of the design.

 ```
 TEST()
 {
   // here I want to replace certain functionality just for this test
    FILE* fopen() { ... }
    void fclose(...) { ... }
    ...
 }
 ```

5. units: something non-intrusive like:

 ```
 var weight = 1 ton + 1 milligramm
 var density = weight / volume // has proper unit
 ```


How all these features could be implemented, I do not know. Perhaps by having them directly supported in language would be the easiest way.

**Comment by jfecher** [comment]
> Languages too often concentrate on theory (let's make everything object oriented with no exception) and ignore user's pain

I agree 100%, that is why Ante is a multi-paradigm language, you are free to use whatever paradigm you feel is best for your scenario.  Just because you may be able to do it one way does not necessarily mean you should.

> Error handling: not needing complicated types because of rare errors ... function signature is not complicated by error handling

I disagree on this point a bit, I do think errors should be present in the function's signature.  That way, users can see at a glance if a function will return an error, and it will be easier for tools to know if a function may return an error as well.  In regard to the complicated types that are rarely used part, my solution to this is just to make types very easy to declare eg.
```
// C++
class MyErrorType
{
public:
    string msg;
    unsigned int errCode;
}

// Ante
type MyErrorType = Str msg, u32 errCode
```

The Ante version is a lot easier to read and has a lot less clutter.

> Tests would be compiled together with the code and invoked automatically at the start.

I definitely agree with your point on unittests.  I feel (like you said) that an easier, shorter syntax encourages the use of more unittests.  I am not sure if unittests will be a first-class feature, but with the current compiler API, it would be easy to implement a unittests library that would look like the following when used:
```
import unittest

![unittest]
fun myTestFn:
    assert(5 > 2)
    ...
```

And as for units, I have not yet focused on them much, but I feel that they could be implemented relatively smoothly if they were annotated similar to type suffixes, eg.
```
let num = 2_u64  //normal type suffix, specify that this literal is a 64 bit unsigned integer (the underscore is optional)

let dogWeight = 60_lbs  //unit suffix

let catWeight = 2kg

let total = dogWeight + catWeight  //what unit am I?
```
I do think this method could work rather smoothly, users would be able to declare new units as well as functions that convert between units.  This would allow the compiler to issue an error if the appropriate conversion was not found as well.  The only things that are left to be decided are small stuff like the unit of the `total` variable above, if two different units are added, which is converted?  Is the r operand always converted to the left's units or vice-versa?  It would probably even be possible to let the user decide this, but unless the user is forced to always decide this, a default must be chosen as well.

**Comment by PavelVozenilek** [comment]
> > Error handling: not needing complicated types because of rare errors ... function signature is not complicated by error handling


> I disagree on this point a bit, I do think errors should be present in the function's signature. That way, users can see at a glance if a function will return an error, and it will be easier for tools to know if a function may return an error as well. In regard to the complicated types that are rarely used part, my solution to this is just to make types very easy to declare

My personal opinion is that this is useless bureaucracy, in most cases. Let say there's call chain A -> B -> C -> D -> E. If E wants also return an error the whole chain needs to updated. More and more typing. Mutual dependency (on error type) grows up.  Low level details bubble up. Worse, if E becomes "error free" nobody would bother to clean up the whole chain. The good initial intent is lost. 

The same problem is with checked exceptions (Java) or const (in C & C++). After a while people "solve" it by declaring the most generic error everywhere and ignoring const.

This kind of information can be tracked by the compiler/IDE. If one really needs to know details in certain place he should be able to express it right there, but not forced to annotate everything.


---------------------

This reminded me another desirable feature.

Let say there's call chain A -> B -> C -> D. Now D needs some parameter. The whole chains has to be updated. Lot of healthy fun with compile-fix-compile cycle. God forbid if parameter is no longer needed at the bottom, who is going through the drudgery to remove it all the way up? 

After a while people declare some big structure which is passed everywhere (or they use globals). But this is also fluff. I would love to be able (e.g. in project file) specify that certain `cfg`  is value that could be passed implicitly and invisibly into every function and it is up to the compiler to find out if it is really used there (and then modify function signature quietly) or not used. 

If such a feature is limited to single value it won't result in chaos.

---------------

```
import unittest

![unittest]
fun myTestFn:
    assert(5 > 2)
    ...
```

This reminds me how language Zig (  https://github.com/andrewrk/zig/issues/128 ) does it. What I do not like:

1. The need to import something. Basic testing infrastructure should be omnipresent.

2. The need to invent a name for a function. This defeats the attempt to make it simple. Inventing names is hard, the result is often unsatisfactory. It doesn't scale. Why the heck do I need to name a test? I had implemented nameless tests in C, C++ and Nim. This allows me to add new one like I am snapping my finger. Thousands of tests in a project are no problem.

**Comment by jfecher** [comment]
> My personal opinion is that this is useless bureaucracy, in most cases. Let say there's call chain A -> B -> C -> D -> E. If E wants also return an error the whole chain needs to updated. More and more typing. Mutual dependency (on error type) grows up. Low level details bubble up.

If E was to be changed to return an error then the whole call chain need not be updated if D handles that error.  If D and all the calling functions wish to instead forward that error then they should be annotated appropriately.  This also distinguishes between functions that can return an error and functions that cannot in trait declarations.  Without it, errors would just be an implementation detail and the user would need to check every function of a library if it returns an error even if the library is just implementing an interface (trait) they know of.

> Worse, if E becomes "error free" nobody would bother to clean up the whole chain. The good initial intent is lost.

This is completely prevented already, if a function signature changes so that no error may be thrown, then an error check at the callsite is not valid because there is no error.  This is another positive side effect of errors being expressed in function return types.

Your second point reminds of a global context variable, that would be very interesting.  I'll definitely consider that down the line.

> 
> ```
> import unittest
> 
> ![unittest]
> fun myTestFn:
>     assert(5 > 2)
>     ...
> ```
> 
> This reminds me how language Zig ( andrewrk/zig#128 ) does it. What I do not like:
> 
> - The need to import something. Basic testing infrastructure should be omnipresent.

This is a side effect of them not being a first class feature.  After thinking about it some more, they could definitely be included as just another compiler directive by default (like they are above).  This would result in the exact same code as the above but without the import, while still allowing users to use external testing libraries if they wish.

>  - The need to invent a name for a function. This defeats the attempt to make it simple. Inventing names is hard, the result is often unsatisfactory. It doesn't scale. Why the heck do I need to name a test? I had implemented nameless tests in C, C++ and Nim. This allows me to add new one like I am snapping my finger. Thousands of tests in a project is no problem.

Naming the function is not necessary, I usually just like to name my tests so I can quickly search for them if I ever need to edit/inspect them.  One could just as easily do the following:
```
![unittest]
fun = assert(5 > 2)
```

**Comment by PavelVozenilek** [comment]
> > My personal opinion is that this is useless bureaucracy, in most cases. Let say there's call chain A -> B -> C -> D -> E. If E wants also return an error the whole chain needs to updated. More and more typing. Mutual dependency (on error type) grows up. Low level details bubble up.

> If E was to be changed to return an error then the whole call chain need not be updated if D handles that error. If D and all the calling functions wish to instead forward that error then they should be annotated appropriately. This also distinguishes between functions that can return an error and functions that cannot in trait declarations. Without it, errors would just be an implementation detail and the user would need to check every function of a library if it returns an error even if the library is just implementing an interface (trait) they know of.

No, the user wouldn't  be left in void. Instead of having formal annotations he would be actually _forced_ to handle errors properly.

Annotations could be created on the fly as IDE hints or in generated documentation. These would be always correct, unlike manually written counterparts.


Imagine this:
```
fun foo -> my_data = 
   ...
   if (...) return :NO_MEMORY
   ...
   if (..) return :SOME_ERROR
   ...
  return real_data
```

1. Error doesn't need to be predefined anywhere. No common header with the litany of all that could go wrong in the world. No need to have add explicit dependency to some obscure library linked by who knows, because they too expose errors. 

2. Signature is simple. No need for monsters like Optional<my_data|my_error>, no painful extraction of anything useful out of them. 

3. Adding or removing error is trivial.



When using such function the compiler would require to handle all errors here and now:
```
// This pushes the error further up. All errors from foo() get also tracked
var x = foo()
if (err) return err
// use x because we know it is valid
```

One may also ignore errors explicitly:
```
var x = foo()
if (err) {} // dangerous
```


If foo() no longer emits errors the compiler would complain:
```
var x = foo()
if (err) return err // will not compile, no error could happen here
```


If one wishes to handle errors individually the compiler would ensure they are all handled:
```
var x = foo()
switch (err) { / exhaustive switch, every possible error has to be handled
  case :NO_MEMORY return err // gets added to the list of tracked errors 
  case :SOME_ERROR ... // handled here, not tracked anymore
  case :NONEXISTENT // this line would fail to compile, no such error
}
// use x safely now
```

After removing certain error from `foo `the compiler would require programmer to remove the unused symbol from relevant places. Obsolete code won't stay forever because no one is sure about it.


There could be syntactic shorthands, like:
```
var x = #foo() // if error happens it will bubble up automatically
// use x safely
```

or
```
// if foo returns error it goes immediately to error handling. 
// It is up to the user to fix the uninitialized x variable
var x = foo().bar().baz() 
switch err ... // handles all errors from foo, bar and baz
```


This solution covers simple errors, those where just the error symbol is enough. This IMO solves majority of use cases. More complicated errors, those that also return data would be handled in traditional way, and it would be up to the programmer to process them correctly. 


-------------------

```
![unittest]
fun = assert(5 > 2)

```

This would solve my complaints.

**Comment by jfecher** [comment]
> No, the user wouldn't be left in void. Instead of having formal annotations he would be actually forced to handle errors properly.

The user would have the formal annotations for reference as to what errors could occur, and they will be forced to handle them properly.

> Signature is simple. No need for monsters like Optional, no painful extraction of anything useful out of them.

If you are very concerned about keeping the signature small, Ante supports (but discourages in APIs) inferred return types
```
fun div: l r =
    if r == 0 then None
    else l / r
```

> ```// It is up to the user to fix the uninitialized x variable```

There are no uninitialized variables in Ante, so this is a big no-no

I think a better way to implement your desired implicit errors would probably be by implementing an error keyword, something like this:
```
//sums up numbers in a file
fun example: Str fileName -> i32
    if not File.exists fileName then error FileNotFound

    let f = InFile fileName
    if isEmpty f then error EmptyFile

    var sum = 0
    //Note that parseInt can return an error, so below is what the proposed error checking would like if it uses the error keyword
    for nums in f.lines().map parseInt do 
        match nums with
        | error e -> error e //forward the error
        | n -> sum += n

    sum
```

I think that this would probably be the best way to implement it _if_ it were implemented.  I am still not sure if I like that there is no error expressed in the return type.  Declaring new errors is much faster, and it is relatively easy to change a function from an errorless one to one that may return an error, but I am still unsure on this tradeoff.  In addition, the `i32` type returned would be a lie because it would actually be wrapped in a compiler-generated error type.  This would be confusing to systems developers who may have expected an `i32` to return as is stated in the signature.  Finally, this also complicates FFI a bit.  Relying on compiler-generated error types would basically force wrapper functions to be made if one wants to use this function in a different language.

**Comment by PavelVozenilek** [comment]
```
fun div: l r =
    if r == 0 then None
    else l / r

```

This is how templates should be done, not a single useless character!


If you find a need to add explicit restrictions on the parameter type: Nim did it in quite a handy way.  Instead of creating named concepts (traits, interfaces, whatever) they just show what they expect.  

For example here is what is expected from a "file type" parameter, in their syntax:
```
type FileLike = generic f
    # reading f returns a string
    var data: string = read(f)

    # writing returns number of bytes written
    var written: int = write(f, String)

    # iteration yields strings
    for line in f:
        line is String

    close(f)
```

http://web.archive.org/web/20160304040540/http://vocalbit.com/posts/exploring-type-classes-in-nimrod.html


Perhaps something like:
```
fun cmp: 't v1 v2 -> int32
    'v1 > v2 is bool and v1 < v2 is bool'
    
    if v1 < v2 then -1
    else if v2 < v1 then +1
    else 0
```

---------------------

A note about syntax:
```
    for nums in f.lines().map parseInt do 
        match nums with
        | error e -> error e //forward the error
        | n -> sum += n
```

It moves the regular (non-error) code to the left, into its own visual scope. This is less readable. 

Compare mostly flat code:
```
var x = foo()
if error -> error
...
... do someting with x
...
var y = bar()
if error -> error
...
... do someting with y
...
var z = baz()
if error -> error
...
... do someting with z
...
```

versus heavily intended:
```
var x = foo()
match x
|  error e -> error e
|  var y = bar()
     match y
     | error e -> error e
     | var z = baz()
          match z
          | error e -> error e
          | ... do someting with z
```
In real world code it would get ugly fast, too much of eye moves, too lenghty.


I think it also doesn't allow to postpone use of non-error result to later
```
var x = foo()
var y = bar()
var z = baz()
if error -> error // handles foo, bar and baz
var res = x + y + z
```

or 
```
var x = foo()
if error -> error
var y = bar()
if error -> error

if a
   if b
      if c -> baz (x, y)
```

-------------

> > // It is up to the user to fix the uninitialized x variable

> There are no uninitialized variables in Ante, so this is a big no-no

That would stay always true:
```
var x = foo()
if error
   -> error // x is uninitialized but it doesn't matter
... use x // compiler is sure x was returned correctly from foo()
```
and

```
var x = foo()
if error ->
   ... // here x has to be initialized, required part of error handling if it continues down

... use x // compiler is sure x was initialized in one or the other way
```


-------------

Error tracking is not the only tracking service compiler may provide. There's also pointer nulability tracking (less useful feature than it sounds) or ability to deduce whether give function allocates dynamic memory somewhere deep inside.

Certain important functions, e.g. public API may be labeled and labels would be statically checked by the compiler:
```
// no unhandled errors ever leave this function, no dynamic allocation happens inside
![errors: [], heap: false]
fun foo = 
   ...
```

Possibly even user defined labels could be supported, say "this function doesn't use file I/O or sockets", for security auditing.

**Comment by jfecher** [comment]
> If you find a need to add explicit restrictions on the parameter type:

Ante already has a way of doing this, but I have to say, I do really like Nim's method.  I will probably draw from it in the future.

> http://web.archive.org/web/20160304040540/http://vocalbit.com/posts/exploring-type-classes-in-nimrod.html

This article is from early 2014, Nim has changed a lot since then, and I believe that concept might be called `concepts` now.  Last I heard of though, they are still unimplemented in Nim.  I do still quite like their syntax though, it is very natural.

```
var x = foo()
match x
|  error e -> error e
|  var y = bar()
     match y
     | error e -> error e
     | var z = baz()
          match z
          | error e -> error e
          | ... do someting with z
```

This code would probably be written more like the following:

```
let x = foo() ? error e -> error e
let y = bar() ? error e -> error e
let z = baz() ? error e -> error e
```

If multiple types of errors are needed to be checked, then you can no longer use the shorthand operator:
```
let x = match foo() with
       | FooErr e -> error e
       | RecoverableErr e -> 0
       | Some n -> n

//if you dont need to do any fancy error recovery, you could probably use the ? operator as long as you
//just want to do the same action for all errors, eg.
let y = bar() ? BarErr | OtherErr e -> error e

let z = baz()  ? BazErr | 0..3 e -> error e
```

> Certain important functions, e.g. public API may be labeled and labels would be statically checked by the compiler ... Possibly even user defined labels could be supported, say "this function doesn't use file I/O or sockets", for security auditing. 

It is already possible (although not yet implemented) to define your own checks such as this.  The beauty of Ante is that the users have just as much control over their program as the compiler does.  If they really wanted to, they could eg. write a parser for a new language and use Ante's compiler to compile their language even as a JIT compiler if they wished.  It is also possible to write a function, as you said, that defines its own compiler directive (lets say it defines ![no_heap]) and checks the parse tree of all functions with that directive to ensure no memory is allocated on the heap.

Sidenote: its possible to have any expression inside ![], single identifiers are just the easiest.

**Comment by PavelVozenilek** [comment]
> This article is from early 2014, Nim has changed a lot since then, and I believe that concept might be called concepts now. Last I heard of though, they are still unimplemented in Nim.

Nim suffers from overambition, and concepts (and dependent types and many other things) have been buggy for years.

----------------

```
let x = match foo() with
       | FooErr e -> error e
       | RecoverableErr e -> 0
       | Some n -> n

//if you dont need to do any fancy error recovery, you could probably use the ? operator as long as you
//just want to do the same action for all errors, eg.
let y = bar() ? BarErr | OtherErr e -> error e

let z = baz()  ? BazErr | 0..3 e -> error e
```

This syntax looks good, only the happy path should not need to be written (I suppose that `Some n -> n` means no-error).

I do not know whether it would be worth to invent some syntax for following cases:

```
var x = foo().bar().baz()
// handle all errors here
```
and 

```
var x = foo()
var y = bar()
var z = baz()
// handle all errors here
```

-----------
Possibly, there could be single exception to all of this, the `no-memory` error.  

Project configuration file could have something like `default_memory_error_handling = true`  settings and  this and only this error would be made invisible, passed up automatically unless it already gets explicitly handled. Available options could be true/false/crash.

My guesstimate is that this could shave off more than half of error handling lines.

**Comment by PavelVozenilek** [comment]
I just read about new release of Rust:
https://blog.rust-lang.org/2016/11/10/Rust-1.13.html

They added "the ? operator", to make error handling easier. Few more years, and they will get rid of these "checked exception" annotations as well.
