### ISSUE TITLE
Apply operators should work with explicit currying

### ISSUE THREAD

**Issue by jfecher** [jfecher/ante#75]
The apply operators `<|` and `|>` should still work when their function parameter is an explicitly curried function. These operators always currently apply their argument to the first argument of the function - with explicit currying the argument should be slotted in wherever the `_` is in the function.

```hs
second a b = b

two = 3 |> second 2
too = 3 |> second _ 2
three = 3 |> second 2 _

four = second 4 <| 5
fore = second _ 4 <| 5
five = second 4 _ <| 5
```

## Estimated work
- The core desugaring may actually already work for this usecase - I'm not sure. If not the apply operators may need a check for explicit currying of their function argument or to check if their argument is already a lambda.
- There should be new parsing tests for this functionality

**Comment by thehabbos007** [comment]
Seems like i have gotten a little stuck on this one.

I found myself writing checking code in the desugaring for the application operators that checked if the underlying thing we're piping into is a lambda, and then doing matching on args and function body to slot in the application operand if arg started with a `$`

I feel like this is somewhat verbose and not that elegant. 

```rust
fn apply_into_lambda<'a>(lambda: ast::Lambda<'a>, arg: Ast<'a>, location: Location<'a>) -> Ast<'a> {
    match *lambda.body {
         Ast::FunctionCall(mut fcall @ ast::FunctionCall{..}) => {
            let argidx =  fcall.args.iter().position(|a| is_arg_explicity_curry(a));

            if let Some(idx) = argidx {
                let to_slot_in = fcall.args.remove(idx)
                // ...
```

Any pointers to how this could be more elegant? Or is the verbose checking of argument identifier values and positions what you had in mind for fixing the slotting in? :)

**Comment by jfecher** [comment]
I think checking for a lambda is the right idea, I don't think you need to check for the `$` argument name though since that'd prevent it from working with lambdas in general. It's expected that something like `foo |> fn a -> a + 3` should probably be equivalent to `(fn a -> a + 3) foo`. Hopefully removing the $ check will allow it to work both with normal lambdas and with the `_` sugar.
As for lambdas with multiple arguments like `foo |> bar _ _`, I think the expected result is probably applying `foo` to the first argument and expecting the type checker to issue a type error later on that the function wasn't applied to enough arguments.

**Comment by thehabbos007** [comment]
I think I might have made some incorrect assumptions, so just making sure before doing something incorrect

Should `too = 3 |> second _ 2` become
a. `too = (fn $1 -> second $1 2) 3` or
b. `too = second 3 2`
after desugaring the apply operator?

I am working toward b, and I believe a is already working.

If we want a, I can simply make sure to add the nice tests instead :)

**Comment by jfecher** [comment]
In terms of runtime semantics I think the two are the same so the distinction isn't the most important but I would say b is preferable if possible since it puts less work on the optimizer. A also requires closures in most cases which aren't implemented yet so that's another point towards b.
