### ISSUE TITLE
Add primitive Ptr type

### ISSUE THREAD

**Issue by jfecher** [jfecher/ante#78]
Currently, ante's only pointer type is `ref` which incurs lifetime inference semantics that aren't always wanted for other pointer types being built on top of it. Since ante is a low-level language it needs a raw pointer type on top of which other types like `Box t` and `Rc t` can be built on top of. Additionally, it should be useful for interfacing with `extern` functions, which currently incorrectly use `ref`.

This PR should include the addition of the `Ptr a` type and changes to the stdlib to update the extern C functions to take or return pointers when possible. The standard `string` type should also probably be
`type string = len: usz, c_string: Ptr char` instead of `type string = len: usz, c_string: ref char`. This is defined in `builtins.rs`.

There doesn't need to be any constructors or anything added to the Ptr type for now, changing the types of `malloc` and `free` in the stdlib should be sufficient to work with them:
```hs
extern
    malloc: usz -> Ptr a
    free: (Ptr a) -> i32
```

## Estimated work
- This sounds more daunting initially than it likely is.
- Adding a `Ptr` to the `Type` union (possibly in `PrimitiveType`?) should give a bunch of compiler errors for incomplete `match`s which should be all the locations that need to be changed within the compiler for this PR.
- The behavior of `Ptr` within each match can almost be copied 1-to-1 with whatever the `ref` type does within that match with anything related to lifetimes removed.
- Since `Ptr` is not a keyword, `Ptr` may have to be defined as a builtin like `string` is in `src/nameresolution/builtins.rs`. `Ptr` shouldn't be as commonly used as `string` though so we may want to in the future move it to another module so users have to explicitly import it. Unfortunately there's no mechanism for defining a builtin type that isn't always in scope yet. Adding this is outside the scope of this PR.

**Comment by jfecher** [comment]
I'm using `Ptr` here over `ptr` mostly because I don't want to reserve the lower-case `ptr` which is commonly used for variable names. This is inconsistent with the other primitive types though.
This raises the question of whether all types should be capitalized (currently all types _except_ primitives are capitalized but that rule of thumb would be broken by this feature).

**Comment by thehabbos007** [comment]
I think I will try to tackle this one :)

Just a question about the implementation: should the new `Ptr` variant in the (primitive) type union take a boxed type as a field representing the `a`? I believe that would make the primitive types non-leaf nodes in a type tree, so perhaps it should be put into the top level type enum?

**Comment by jfecher** [comment]
I'm thinking `Ptr` can be in the primitive type enum - it doesn't need any associated data with it since `Ptr a` can be represented as `TypeApplication(Ptr, vec![TypeVariable a])`. I think `ref` used to be a PrimitiveType at one point before it had an associated lifetime variable so you may be able to look in the git history for inspiration

**Comment by thehabbos007** [comment]
Haven't left this, just need to find some spare time to continue FYI :)

**Comment by jfecher** [comment]
No problem, thanks for the update :+1: 

My work on the z3 branch has actually been slowed down too - my laptop broke recently and I've been setting up a new one.

**Comment by thehabbos007** [comment]
Hey, hope you are doing well, friend :)

I have some questions about registering the Ptr type.
I've tried doing it like it's doen for string/pair, and this is what i have
```rust
fn define_ptr<'a>(cache: &mut ModuleCache<'a>) -> Type {
    let location = Location::builtin();

    let type_var_id = cache.next_type_variable_id(LetBindingLevel(0));
    let type_vars = vec![Type::TypeVariable(type_var_id)];
    let ptr = Type::Primitive(PrimitiveType::Ptr);
    let name = "Ptr".to_owned();
    let ptr_id = cache.push_type_info(name.clone(), vec![type_var_id], location);
    assert_eq!(ptr_id, PTR_TYPE);
    
    let ptr_type = Box::new(Type::TypeApplication(Box::new(ptr), type_vars.clone()));
    let type_def = Type::ForAll(vec![type_var_id], ptr_type);

    let id = cache.push_definition(&name, false, location);
   
    // If we don't want constructors for Ptr, do i need to omit these 3 lines?
    let constructor = DefinitionKind::TypeConstructor { name, tag: None };
    cache.definition_infos[id.0].typ = Some(type_def);
    cache.definition_infos[id.0].definition = Some(constructor);
    Type::UserDefinedType(PTR_TYPE)
}
```
And I'm calling `define_ptr` in `type_infos` where `define_string` also is called.

But there still seems to be the following errors
```
   | /home/ahmad/.config/ante/stdlib/prelude.an: 15,20  error: Type Ptr was not found in scope
   |     malloc: usz -> Ptr a
```

I don't think I quite understand where the type is registered for the user to use.

No need to rush on answering this!

**Comment by jfecher** [comment]
That snippet should define the type and constructor (though, I think you also still need to set the generic args of the type as seen here: https://github.com/jfecher/ante/blob/master/src/nameresolution/builtin.rs#L125), after that you also need to import the type into scope as if it was defined in the prelude, this is done for the pair type here: https://github.com/jfecher/ante/blob/master/src/nameresolution/builtin.rs#L71-L74
I don't think it is actually done for the string constructor yet which is a bug
