### ISSUE TITLE
enums

### ISSUE THREAD

**Issue by PavelVozenilek** [jfecher/ante#8]
Few suggestions to improve enums.

1. `match` on enums should require complete list of values, w/o the default (default would defeat the intention and may result in bug when another enum item is added later).

2. Some enums may want to use global namespace (like in C):

 `enum foo -> .Bar .Baz`  (accomplished by the leading dot)

 Both `Bar` and `foo.Bar` would be valid names.  If the enum is very important for the application and used often short name is enough.

3. Enum may be assigned string, to be directly usable in string context:

 ```
  enum Foo ->
    bar = "My Name 1"
    baz = "My Name 2"

 ```
  Default would be the stringified symbol. Empty string or nil may mean no automatic stringification.

4. Aliases. This may be useful for SCADA applications where some cryptical names from the documentation have informal aliases.

 ```
 enum Foo ->
    NR_27_F7_3 = wheel 
    NR_00_H2_0
    NR_12_O3_1 = engine

 ```  
 Formal name and alias could be used interchangeably.

5. Enums may be defined "inline" together with related functions, to give a hint that these constructs belong together.

 ```
 // when return value is anonymous enum
 fun foo -> enum Bar Baz // namespace of Bar & Baz is foo

 var res = foo()

 match res with
    foo.Bar -> 
     foo.Baz ->
 ```

 and

 ```
 // when parameter is anonymous enum
 fun foo : (enum Bar Baz) param = 

 foo(Bar)
 ```

 and non-anonymous variants

 ```
 fun foo -> enum xyz -> Bar Baz 

 var foo.xyz res = foo()
 ```

 ```
 fun foo : (enum xyz -> Bar Baz) param 

 foo(xyz.Bar)
 ```
 Non-anonymous inlined enums would need to be used in "function context", meaning inside the block which calls the function, not separately or as a member of some structure. Restriction on use of the symbol should avoid misuse.

6. Enum as valid integer range plus sideband value(s):

 ```
 enum FooResult ->
    NO_MEMORY // automatically assigned value outside valid result range, e.g. 101
    SOME_OTHER_ERROR
    1 .. 100 // valid results

   fun foo -> FooResult  = ...

  match foo() with -> // exhaustive match
    1 .. 50 -> 
    51 .. 100 ->
    NO_MEMORY ->
    SOME_OTHER_ERROR ->
 ```
 Here `foo()` may return valid result (the number) or error. No need to create complicated types which need more memory or to pretend that some magic number (-1) means error and hope programmer won't forget about it.
  
--------------
Complex example:

```
enum Foo ->
  Bar = 1 = something = "Bar"
  Baz  // = 2 = "Baz"
  Grr = "Hmm" // = 3
  Frr = .wheel // = 4 = "Frr",  'wheel' symbol is in global namespace

```

**Comment by jfecher** [comment]
You are right, enums need quite a bit of work, and even the standard is quite outdated in describing them.  The current (already implemented) syntax of creating an enum is to make a tagged union type without any extension types, the same way you would make an enum in most functional languages:

type MyEnum = Val1 | Val2 | Val3

For scoping rules, each member is currently in the global namespace by default unless the module it is imported from is imported under an alias.

Ok, onto the unimplemented stuff.
Converting an enum value to a Str by default results in the stringified version of its symbol, eg. `Str Val1 == "Val1"`

Changing this behaviour currently requires overloading the Str cast function.  Providing an alternative default within the type definition as you suggested would be much terser.  I'm not sure about the syntax, but it may grow on me.

Also, in regard to your first point, `match` already requires an exhaustive list of values.  I am not sure where in the standard it is used incorrectly, but I will fix this soon.  If you are using match in Ante code currently, the error checking for match expressions is not as complete as I would like, so it most likely just would not have caught that not all cases were accounted for without a default.
