### ISSUE TITLE
static & dynamic array unification

### ISSUE THREAD

**Issue by PavelVozenilek** [jfecher/ante#9]
This is (only half baked) idea to unify static and dynamic arrays use. Static arrays and dynamic arrays (vectors) usually have different syntax leading to manual duplication of generics. Static ones are prone to degradation to pointers.

Reading `language.am` I think they are distinct now (because of the array -> pointer conversion).

Whether array is static or dynamic can be (I guess) deduced from its declaration. This information can be then used by the compiler.

If a function has static array as a parameter it would also secretly pass the known fixed size as parameter and current size as another one (I think this is needed to implement the ++= operator).

If a function has dynamic array as a parameter it would take pointer to its "vector" structure.

If a function is called with static array in one place and with dynamic array in another then the code (either source or AST) would be cloned and modified to handle both variants. Similarly for templates, they would be instantiated according to their use.

If a function has several array parameters then clones would be created for all combinations which were found. 

Taking pointer to such functions would not be allowed by the compiler (because the clones cannot be distinguished by name).

Array as member of structure/tuple would not require any special handling.

If implemented then conversion of arrays to pointers could be perhaps dropped (except for FFI) and pointer arithmetic as well. I had never used pointer arithmetic anywhere but in degraded array context.

I do not have clear picture for multidimensional array. (I never used such a beast.)

**Comment by jfecher** [comment]
I am debating even including static arrays in Ante.  The array literals you see will most likely be a vector-like type by default and thus will already have the size included.  For me, it is extremely rare when I would ever use a static array, and a dynamic array would still be valid in all of those scenarios.  Furthermore, since vectors would be first class citizens, the compiler would know about them and know when the size value could be optimized away.

**Comment by PavelVozenilek** [comment]
> I am debating even including static arrays in Ante.

This sounds reasonable (to give them up).  If Ante will have the ability to use custom allocators then one could carve up part of the stack, make arena allocator and it would have the same layout and the same speed as static array sitting there. Short arrays inside structures (like 2D/3D points) could be turned into handful of named members, long arrays would only hog the cache.

The language converts variable number of arguments into static array. This should be taken into consideration.


I though about my idea a bit and got a counter-example: say I want to have array container of owned pointers (self deleting pointers). This can be rather easily implemented as an object but it would not (easily) fit into the unified array idea. 

I am closing this for good.
