### ISSUE TITLE
what You thing about using more unicode characters

### ISSUE THREAD

**Issue by sp00ck** [jfecher/ante#98]
not only this on keyboard
mebye using both
-> arrow https://unicode-table.com/en/sets/arrow-symbols/
meybe other too?

**Comment by jfecher** [comment]
This may be something I allow as an alternative in the future but for the time being it is relatively unnecessary.

If someone else wanted to add some unicode alternatives for symbols like `->`, `|>`, or `<|` in ante I wouldn't object but I'll be too busy with larger feature / bugfix tasks for quite some time before I consider this.
